CREATE TABLE USERS (
	ID VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	UNAME VARCHAR(10) DEFAULT "",
	BIRTH DATE,
	SEX CHAR(1) DEFAULT "M",
	TYPE CHAR(1) DEFAULT "C",
	PRIMARY KEY (ID),
	CHECK (SEX='M' OR SEX='F'),
	CHECK (TYPE='C' OR TYPE='M' OR TYPE='A')
);

CREATE TABLE CAFES (
	CNAME VARCHAR(20) NOT NULL,
	PHONE VARCHAR(15),
	LOCATION VARCHAR(100),
	MANAGER VARCHAR(20),
	PRIMARY KEY (CNAME),
	FOREIGN KEY (MANAGER)
		REFERENCES USERS(ID)
);

CREATE TABLE COUPON (
	COUPON_ID INT NOT NULL AUTO_INCREMENT,
	CNUMBER INT UNSIGNED NOT NULL DEFAULT 0,
	CUSTOMER VARCHAR(20),
	CAFE VARCHAR(20),
	CHECK (CNUMBER <= 10),
	PRIMARY KEY (COUPON_ID),
	UNIQUE (CUSTOMER, CAFE),
	FOREIGN KEY (CUSTOMER)
		REFERENCES USERS(ID)
		ON DELETE CASCADE,
	FOREIGN KEY (CAFE)
		REFERENCES CAFES(CNAME)
);

CREATE TABLE MENUS (
	MENUID INT NOT NULL AUTO_INCREMENT,
	CAFE VARCHAR(20) NOT NULL,
	MNAME VARCHAR(20) NOT NULL,
	CALORIE INT UNSIGNED,
	PRICE INT UNSIGNED,
	STOCK INT UNSIGNED,
	PRIMARY KEY (MENUID),
    UNIQUE (CAFE, MNAME),
	FOREIGN KEY (CAFE)
		REFERENCES CAFES(CNAME)
);

CREATE TABLE BEVERAGES (
	MENU INT NOT NULL,
	TEMPERATURE CHAR(1),
	SIZE CHAR,
	CHECK (TEMPERATURE='H' OR TEMPERATURE='C'),
	FOREIGN KEY (MENU)
		REFERENCES MENUS(MENUID)
);

CREATE TABLE DESSERT (
	MENU INT NOT NULL,
	MFD DATE,
	EXP DATE,
	FOREIGN KEY (MENU)
		REFERENCES MENUS(MENUID)
);

CREATE TABLE ORDERS (
	ISSUE_TIME TIME NOT NULL,
	CUSTOMER VARCHAR(20),
	CAFE_NAME VARCHAR(20),
	MENU INT NOT NULL,
	FOREIGN KEY (CUSTOMER)
		REFERENCES USERS(ID)
		ON DELETE CASCADE,
	FOREIGN KEY (CAFE_NAME)
		REFERENCES CAFES(CNAME),
	FOREIGN KEY (MENU)
		REFERENCES MENUS(MENUID)
);

CREATE TABLE INGREDIENT (
	MENU INT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	FOREIGN KEY (MENU)
		REFERENCES MENUS(MENUID)
        ON DELETE CASCADE
);

CREATE TABLE POST (
	POST_ID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	POST_DATE DATE NOT NULL,
	CONTENT VARCHAR(1024),
	CAFE VARCHAR(20) NOT NULL,
	PRIMARY KEY (POST_ID),
	FOREIGN KEY (CAFE)
		REFERENCES CAFES(CNAME)
);